name: DEJFChestHoppers
version: 1.2
author: Dejf
main: cf.dejf.DEJFChestHoppers.DEJFChestHoppers
commands:
  hoppers:
    description: Check all hoppers and their coordinates.
    usage: /hoppers
    permission: DEJFChestHoppers.hoppers
    permission-message: You don't have permission mate.
